// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Thermostat

#ifndef _THERMOSTAT_UI_H
#define _THERMOSTAT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

    // SCREEN: ui_Home
    void ui_Home_screen_init(void);
    extern lv_obj_t *ui_Home;
    extern lv_obj_t *ui_Arc_Group;
    void ui_event_Arc1(lv_event_t *e);
    extern lv_obj_t *ui_Arc1;
    extern lv_obj_t *ui_Temp_Bg;
    extern lv_obj_t *ui_Temp_Num_Bg;
    extern lv_obj_t *ui_Label_Celsius;
    // CUSTOM VARIABLES

    // EVENTS

    extern lv_obj_t *ui____initial_actions0;

    // FONTS
    LV_FONT_DECLARE(ui_font_Number);

    // UI INIT
    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
