// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView2 = lv_tabview_create(ui_Screen2, LV_DIR_LEFT, 50);
    lv_obj_set_width(ui_TabView2, 270);
    lv_obj_set_height(ui_TabView2, 220);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TabView2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TabPage1 = lv_tabview_add_tab(ui_TabView2, "Online");

    ui_Spinner3 = lv_spinner_create(ui_TabPage1, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 80);
    lv_obj_set_height(ui_Spinner3, 80);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "Calendar");

    ui_Calendar3 = lv_calendar_create(ui_TabPage2);
    lv_calendar_set_today_date(ui_Calendar3, 2024, 12, 17);
    lv_calendar_set_showed_date(ui_Calendar3, 2024, 12);
    lv_obj_t * ui_Calendar3_header = lv_calendar_header_arrow_create(ui_Calendar3);
    lv_obj_set_width(ui_Calendar3, 200);
    lv_obj_set_height(ui_Calendar3, 200);
    lv_obj_set_x(ui_Calendar3, -8);
    lv_obj_set_y(ui_Calendar3, -8);
    lv_obj_set_align(ui_Calendar3, LV_ALIGN_CENTER);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView2, "Setting");

    ui_Slider4 = lv_slider_create(ui_TabPage3);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 150);
    lv_obj_set_height(ui_Slider4, 10);
    lv_obj_set_x(ui_Slider4, 3);
    lv_obj_set_y(ui_Slider4, 1);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);


    ui_Checkbox2 = lv_checkbox_create(ui_TabPage3);
    lv_checkbox_set_text(ui_Checkbox2, "Enable Auto Scan");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, -25);
    lv_obj_set_y(ui_Checkbox2, 38);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Switch2 = lv_switch_create(ui_TabPage3);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 45);
    lv_obj_set_y(ui_Switch2, -90);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Label8 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -70);
    lv_obj_set_y(ui_Label8, -90);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "WI-FI");

    ui_Label9 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -59);
    lv_obj_set_y(ui_Label9, -61);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Bluetooth");

    ui_Switch3 = lv_switch_create(ui_TabPage3);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 45);
    lv_obj_set_y(ui_Switch3, -60);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);


    ui_Label10 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -63);
    lv_obj_set_y(ui_Label10, -30);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Volume");

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
